<?php

namespace AppBundle\Repository;

/**
 * AutrePaiementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AutrePaiementRepository extends \Doctrine\ORM\EntityRepository
{
}
