<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
* EmploisTpsRepository
* This class was generated by the Doctrine ORM. Add your own custom
* repository methods below.
*/
class EmploiTpsRepository extends EntityRepository {
    
    public function findByClasse($classe, $jour, $prof, $anSco,$semaine, $user = null, $site = null) {
        $criteres = '';
        $param = [];
        
        if ($anSco) {
            $criteres .= ' e.anScolaire = :anSco ';
            $param['anSco'] = $anSco;
        }

        if ($semaine) {
            $criteres .= ' AND e.semaine = :semaine ';
            $param['semaine'] = $semaine;
        }
        
        if ($prof) {
            $criteres .= ' AND e.prof = :prof ';
            $param['prof'] = $prof;
        }
        
        if ($site) {
            $criteres .= 'AND e.site = :site ';
            $param['site'] = $site;
        }
        if ($classe) {
            $criteres .= 'AND e.classe = :classe ';
            $param['classe'] = $classe;
        }
        
        if ($jour) {
            $criteres .= 'AND e.jour = :jour ';
            $param['jour'] = $jour;
        }
        
        if ($user) {
            $criteres .= 'AND e.user = :user ';
            $param['user'] = $user;
        }
        if($classe==null && $jour==null && $prof==null && $site==null && $anSco==NULL){
            $sql = "SELECT e, cl, prof, mat, an FROM AppBundle\Entity\EmploiTps e "
            . "JOIN e.prof prof "
            . "JOIN e.classe cl "
            . "JOIN e.matiere mat "
            . "JOIN e.anScolaire an "
            . "ORDER BY e.id DESC";
        }
        else{
            $sql = "SELECT e, cl, prof, mat, an FROM AppBundle\Entity\EmploiTps e "
            . "JOIN e.prof prof "
            . "JOIN e.classe cl "
            . "JOIN e.matiere mat "
            . "JOIN e.anScolaire an "
            . "WHERE "
            . $criteres
            . "ORDER BY e.id DESC";
        }
        
        
        $query = $this->_em->createQuery($sql);
        $query->setParameters($param);
        
        return $query->getResult();
    }
    
    public function findListByClasse($classe, $jour, $prof, $anSco, $semaine, $user = null, $site = null) {
        $criteres = '';
        $param = [];
        
        if ($anSco) {
            $criteres .= ' e.anScolaire = :anSco ';
            $param['anSco'] = $anSco;
        }
        if ($semaine) {
            $criteres .= ' AND e.semaine = :semaine ';
            $param['semaine'] = $semaine;
        }
        
        if ($prof) {
            $criteres .= ' AND e.prof = :prof ';
            $param['prof'] = $prof;
        }
        
        if ($site) {
            $criteres .= 'AND e.site = :site ';
            $param['site'] = $site;
        }
        if ($classe) {
            $criteres .= 'AND e.classe = :classe ';
            $param['classe'] = $classe;
        }
        
        if ($jour) {
            $criteres .= 'AND e.jour = :jour ';
            $param['jour'] = $jour;
        }
        
        if ($user) {
            $criteres .= 'AND e.user = :user ';
            $param['user'] = $user;
        }
        if($classe==null && $jour==null && $prof==null && $site==null && $anSco==NULL){
            $sql = "SELECT cl,an ,e, prof, mat  FROM AppBundle\Entity\EmploiTps e "
            . "JOIN e.prof prof "
            . "JOIN e.classe cl "
            . "JOIN e.matiere mat "
            . "JOIN e.anScolaire an "
            . "ORDER BY e.id DESC";
        }
        else{
            
            $sql = "SELECT  e FROM AppBundle\Entity\EmploiTps e "
            . "WHERE "
            . $criteres
            . "ORDER BY e.id DESC";
            
            /*  $sql = "SELECT distinct an.nom as clas, cl, an,e, prof, mat, si FROM AppBundle\Entity\EmploiTps e "
            . "JOIN e.prof prof "
            . "JOIN e.classe cl "
            . "JOIN e.matiere mat "
            . "JOIN e.anScolaire an "
            . "JOIN e.site si "
            . "WHERE "
            . $criteres
            . "ORDER BY e.id DESC"; */
        }
        
        
        $query = $this->_em->createQuery($sql);
        $query->setParameters($param);
        
        // var_dump($query);
        return $query->getResult();
    }
    
    public function findOneBySiteAnCLasse($classe,$anSco,$site, $semaine) {
        $criteres = '';
        $param = [];
        
        if ($anSco) {
            $criteres .= ' e.anScolaire = :anSco ';
            $param['anSco'] = $anSco;
        }
        
        
        if ($site) {
            $criteres .= 'AND e.site = :site ';
            $param['site'] = $site;
        }

        if ($semaine) {
            $criteres .= 'AND e.semaine = :semaine ';
            $param['semaine'] = $semaine;
        }
        if ($classe) {
            $criteres .= 'AND e.classe = :classe ';
            $param['classe'] = $classe;
        }
        
        
        
        $sql = "SELECT  e FROM AppBundle\Entity\EmploiTps e "
        . "WHERE "
        . $criteres
        . "ORDER BY e.id DESC";
        
        
        
        $query = $this->_em->createQuery($sql);
        $query->setParameters($param)->setMaxResults(1);
        
        // var_dump($query);
        return $query->getOneOrNullResult();
    }

    public function findAllBySiteAnCLasse($classe,$anSco,$site, $semaine) {
        $criteres = '';
        $param = [];
        
        if ($anSco) {
            $criteres .= ' e.anScolaire = :anSco ';
            $param['anSco'] = $anSco;
        }
        
        
        if ($site) {
            $criteres .= 'AND e.site = :site ';
            $param['site'] = $site;
        }

        if ($semaine) {
            $criteres .= 'AND e.semaine = :semaine ';
            $param['semaine'] = $semaine;
        }
        if ($classe) {
            $criteres .= 'AND e.classe = :classe ';
            $param['classe'] = $classe;
        }
        
        
        
        $sql = "SELECT  e FROM AppBundle\Entity\EmploiTps e "
        . "WHERE "
        . $criteres
        . "ORDER BY e.id DESC";
        
        
        
        $query = $this->_em->createQuery($sql);
        $query->setParameters($param);
        
        // var_dump($query);
        return $query->getResult();
    }

    public function findCoursNonEffectues($site, $anScolaire)
    {
        $qb = $this->createQueryBuilder('e')
        ->leftJoin(
            'AppBundle:Cours',
            'c',
            'WITH',
            'c.prof = e.prof AND
             c.classe = e.classe AND 
             c.matiere = e.matiere AND 
             c.site = e.site AND 
             c.jour = e.jour AND
             c.anScolaire = e.anScolaire'
        )
        ->where('e.site = :site')
        ->andWhere('e.anScolaire = :anScolaire')
        ->setParameter('site', $site)
        ->setParameter('anScolaire', $anScolaire)
        ->orderBy('e.classe', 'ASC')
        ->addOrderBy('e.semaine', 'ASC')
        ->addOrderBy('e.jour', 'ASC');
        ;

        $emplois = $qb->getQuery()->getResult();

        $coursNonEffectues = [];
        foreach ($emplois as $emploi) {
        $annee = $emploi->getAnnee();
        $semaine = $emploi->getSemaine();

        // Calcule les dates de la semaine de l'emploi du temps
        $start = new \DateTime();
        $start->setISODate($annee, $semaine);
        $start->setTime(0, 0, 0);

        $end = clone $start;
        $end->modify('+6 days')->setTime(23, 59, 59);

        // Rechercher si un cours a été effectué cette semaine-là
        $cours = $this->_em->getRepository('AppBundle:Cours')->createQueryBuilder('c')
            ->where('c.prof = :prof')
            ->andWhere('c.classe = :classe')
            ->andWhere('c.matiere = :matiere')
            ->andWhere('c.site = :site')
            ->andWhere('c.anScolaire = :anScolaire')
            ->andWhere('c.date BETWEEN :start AND :end')
            ->setParameters([
                'prof' => $emploi->getProf(),
                'classe' => $emploi->getClasse(),
                'matiere' => $emploi->getMatiere(),
                'site' => $emploi->getSite(),
                'anScolaire' => $emploi->getAnScolaire(),
                'start' => $start,
                'end' => $end,
            ])
            ->getQuery()
            ->getResult();

        // Si aucun cours trouvé dans la semaine correspondante → non effectué
        if (!$cours) {
            $coursNonEffectues[] = $emploi;
        }
    }

    return $coursNonEffectues;

        // $query = $this->createQueryBuilder('e')
        //     ->leftJoin(
        //         'AppBundle:Cours',
        //         'c',
        //         'WITH',
        //         'c.prof = e.prof AND
        //          c.classe = e.classe AND 
        //          c.matiere = e.matiere AND 
        //          c.site = e.site AND 
        //          c.jour = e.jour AND
        //          c.anScolaire = e.anScolaire'
        //     )
        //     ->where('e.site = :site')
        //     ->andWhere('e.anScolaire = :anScolaire')
        //     ->andWhere('c.id IS NULL')
        //     ->andWhere('WEEK(c.date, 1) = e.semaine') 
        //     ->setParameter('site', $site)
        //     ->setParameter('anScolaire', $anScolaire)
        //     ->getQuery();

        // $results = $query->getResult();
        // return $results;  
        
    }

    public function findCoursConflitProf($prof, $semaine, $jour, $debut, $fin,$anneeSco, $excludeId = null)
    {
        $qb = $this->createQueryBuilder('c')
            ->where('c.prof = :prof')
            ->andWhere('c.semaine = :semaine')
            ->andWhere('c.jour = :jour')
            ->andWhere('c.anScolaire = :anneeSco')
            ->andWhere('(c.debut < :fin AND c.fin > :debut)') // chevauchement
            ->setParameters([
                'prof' => $prof,
                'semaine' => $semaine,
                'jour' => $jour,
                'debut' => $debut,
                'fin' => $fin,
                'anneeSco' => $anneeSco
            ]);

        if ($excludeId) {
            $qb->andWhere('c.id != :id')->setParameter('id', $excludeId);
        }

        return $qb->getQuery()->getResult();
    }
    
    
    
}
