<?php

namespace AppBundle\Repository;

/**
 * EtudiantLastClasseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtudiantLastClasseRepository extends \Doctrine\ORM\EntityRepository
{
}
