<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Etudiant;
use Doctrine\ORM\EntityRepository;

/**
 * NoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluationRepository extends EntityRepository
{

    public function getEvaluation($id)
    {
        $sql = 'select ev, cl, mat, per, an from AppBundle:Evaluation ev '
            . 'join ev.classe cl '
            . 'join ev.matiere mat '
            . 'join ev.periode per '
            . 'join ev.anScolaire an '
            . 'where ev.id = :id';
        return $query = $this->_em->createQuery($sql)
            ->setParameter('id', $id)
            ->getOneOrNullResult();
    }

    public function getEvaluationsByEtudiant(Etudiant $etudiant)
    {
        $query = 'SELECT an.id AS aid, an.nom AS annee, ' .
            'per.id AS pid, per.nom AS periode, ' .
            'cl.id AS cid, cl.code AS classe ' .
            'FROM sf3_evaluation ev ' .
            'JOIN sf3_an_scolaire an ON an.id = ev.an_scolaire_id ' .
            'JOIN sf3_periode per ON per.id = ev.periode_id ' .
            'JOIN sf3_classe cl ON cl.id = ev.classe_id ' .
            'JOIN sf3_note nt ON ev.id = nt.evaluation_id ' .
            'WHERE nt.etudiant_id = :eid ' .
            'GROUP BY an.id, cl.id, per.id ' .
            'ORDER BY an.nom DESC, cl.nom ASC, per.id ASC ';
        $db = $this->_em->getConnection();
        $stmt = $db->executeQuery($query, ['eid' => $etudiant->getId()]);
        return $stmt->fetchAll();
    }

}
