<?php

namespace AppBundle\Repository;

/**
 * GroupeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupRepository extends \Doctrine\ORM\EntityRepository {

    public function liste() {
        return $this->createQueryBuilder('g')
                        ->select('g')
                        ->where('g.role NOT LIKE :role')
                        ->setParameter('role', 'ROLE_SUPER_ADMIN')
                        ->getQuery()
                        ->getResult();
    }

}
