<?php

namespace AppBundle\Repository;

/**
 * LeconRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeconRepository extends \Doctrine\ORM\EntityRepository
{
}
